# Copyright 2023 XigXog
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

apiVersion: apps/v1
kind: Deployment
{{ include "metadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "selectors" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
      annotations:
        {{- include "annotations" . | nindent 8 }}
    spec:
      {{- include "podSpec" . | nindent 6 }}
      initContainers:
        - {{- include "bootstrap" . | nindent 10 }}
      containers:
        - name: {{ .Component.Name }}
          image: {{ .Component.Image | quote }}
          imagePullPolicy: {{ .Component.ImagePullPolicy | default "IfNotPresent" }}
          {{- include "securityContext" . | nindent 10 }}
          {{- include "resources" . | nindent 10 }}
          {{- include "probes" . | nindent 10 }}
          args:
            - -platform={{ .Platform.Name }}
            - -name={{ .Component.Name }}
            - -hash={{ .BuildInfo.HTTPSrvCommit }}
            - -pod=$(KUBEFOX_COMPONENT_POD)
            - -http-addr=0.0.0.0:8080
            - -https-addr=0.0.0.0:8443
            - -broker-addr={{ .Platform.BrokerAddr }}
            - -health-addr=0.0.0.0:1111
            - -max-event-size={{ .Values.maxEventSize }}
            - -log-format={{ .Telemetry.Logs.Format | default "json" }}
            - -log-level={{ .Telemetry.Logs.Level | default "info" }}
          env:
          {{- include "env" . | nindent 12 }}
            - name: KUBEFOX_COMPONENT_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBEFOX_COMPONENT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ .Platform.Name }}-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: health
              containerPort: 1111
              protocol: TCP
          volumeMounts:
            - name: root-ca
              mountPath: {{ homePath }}/ca.crt
              subPath: ca.crt
            - name: kubefox
              mountPath: {{ homePath }}
      volumes:
        - name: root-ca
          configMap:
            name: {{ .Instance.Name }}-root-ca
        - name: kubefox
          emptyDir: {}