site_name: KubeFox
site_url: https://docs.kubefox.io
repo_url: https://github.com/xigxog/kubefox
edit_uri: edit/main/docs
docs_dir: 'docs'
repo_name: xigxog/kubefox
site_description: Documentation for KubeFox
site_author: John Long
copyright: Copyright © XigXog

use_directory_urls: false

extra:
  homepage: https://kubefox.io
  social:
    - icon: fontawesome/solid/house
      link: https://kubefox.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/xigxog/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kubefox
    - icon: fontawesome/brands/github
      link: https://github.com/xigxog/kubefox

extra_css:
  - stylesheets/extra.css
  - stylesheets/fonts.css

theme:
  name: material
  logo: images/kubefox-logo-black.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: deep orange
      # Palette toggle for light mode
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: orange
      # Palette toggle for dark mode
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

plugins:
  - awesome-pages
  - mermaid2
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative $config_dir # relative to the current Markdown file
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - toc:
      permalink: false
      toc_depth: 3
